name: "Check pip dependencies"

on:
  pull_request:
    branches:
      - main
    paths:
      - api/Pipfile
  push:
    branches:
      - main
    paths:
      - api/Pipfile
  schedule:
    - cron: "0 19 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.12"
  API_DIRS: ./api

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.API_DIRS }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code from GitHub
        uses: actions/checkout@v5
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Setup pipenv
        run: |
          pip install --user pipenv
      # This job will exit when dependencies error occurs
      - name: Run pipenv lock.
        run: |
          pipenv lock --dev
      - name: Upload Pipfile.lock as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pipfile.lock
          path: ${{ env.API_DIRS }}/Pipfile.lock
